#!/usr/bin/env python3
"""
Convert all PNG images in H5_code/assets to WebP base64 data URIs
and generate a JavaScript mapping file.
Run with: python3 embed_images.py
"""
import base64
import io
import json
import os
import sys
from pathlib import Path

from PIL import Image

BASE_DIR = Path("/home/wlll_agent/H5_code")
ASSETS_DIR = BASE_DIR / "assets" / "images" / "types"
OUTPUT_JS = BASE_DIR / "images_embedded.js"

def convert_image_to_webp_base64(filepath: Path) -> str:
    """Convert an image to WebP base64 data URI."""
    try:
        img = Image.open(filepath)
        # Convert RGBA to RGB if needed (WebP supports alpha, but keep original mode)
        buf = io.BytesIO()
        # Save as WebP quality 80
        img.save(buf, format="WEBP", quality=80)
        b64 = base64.b64encode(buf.getvalue()).decode("ascii")
        return f"data:image/webp;base64,{b64}"
    except Exception as e:
        print(f"ERROR converting {filepath}: {e}", file=sys.stderr)
        return None

def main():
    if not ASSETS_DIR.exists():
        print(f"ERROR: {ASSETS_DIR} not found", file=sys.stderr)
        sys.exit(1)
    
    # Find all PNG files
    png_files = sorted(ASSETS_DIR.rglob("*.png"))
    total = len(png_files)
    print(f"Found {total} PNG images to convert")
    
    images_map = {}
    total_size_kb = 0
    converted_count = 0
    
    for i, png_path in enumerate(png_files, 1):
        # Get relative path from 'types/' directory
        rel = png_path.relative_to(ASSETS_DIR)
        # Remove extension
        key = str(rel.with_suffix(""))
        # Normalize path separators
        key = key.replace("\\", "/")
        
        # Get original size
        orig_size = png_path.stat().st_size
        orig_size_kb = orig_size / 1024
        
        print(f"[{i}/{total}] Converting {key} ({orig_size_kb:.0f}KB)...", end=" ", flush=True)
        
        data_uri = convert_image_to_webp_base64(png_path)
        if data_uri is None:
            print("SKIPPED")
            continue
        
        # Calculate webp size
        webp_size = len(data_uri) * 3 / 4  # Approximate from base64 length
        webp_size_kb = webp_size / 1024
        total_size_kb += webp_size_kb
        converted_count += 1
        
        images_map[key] = data_uri
        print(f"→ {webp_size_kb:.0f}KB ({orig_size_kb/webp_size_kb:.1f}x compression)")
    
    # Write JavaScript mapping
    print(f"\nWriting {OUTPUT_JS} with {converted_count} images ({total_size_kb/1024:.1f}MB total)...")
    
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write("// Auto-generated image data URIs (WebP base64)\n")
        f.write("// Generated by embed_images.py\n")
        f.write(f"// {converted_count} images, ~{total_size_kb/1024:.1f}MB total\n")
        f.write("const IMAGES = {\n")
        
        for key, data_uri in images_map.items():
            # Escape the key properly
            escaped_key = json.dumps(key, ensure_ascii=False)
            f.write(f"  {escaped_key}: {json.dumps(data_uri, ensure_ascii=False)},\n")
        
        f.write("};\n")
    
    output_size = OUTPUT_JS.stat().st_size
    print(f"Done! JS file size: {output_size/1024/1024:.1f}MB")
    print(f"Average compression: {total_size_kb/converted_count:.0f}KB per image")

if __name__ == "__main__":
    main()
